name: "get-SARI-data"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 5"   

jobs:
  get-SARI-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install libcurl4-openssl-dev
        sudo add-apt-repository -y ppa:cran/poppler
        sudo apt-get update
        sudo apt-get install -y libpoppler-cpp-dev
        sudo apt-get install -y libwebp-dev
        sudo apt install -y tesseract-ocr
        sudo apt-get install pdftk 
        sudo add-apt-repository universe
        sudo add-apt-repository ppa:inkscape.dev/stable
        sudo apt-get update
        sudo apt install inkscape 
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
          r-version: 4.1.0
       
        
    - name: Get latest SARI data
      run: Rscript ./code/get_weekly_sari_data.R
        
    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/KITmetricslab/RESPINOW-Data.git > /dev/null 2>&1
        git pull origin main
        git add --all
        git commit --allow-empty -m "Update SARI data"
        
    - name: Push changes
      run: |
        git push --quiet --set-upstream origin HEAD:main
        echo "pushed to github"
