name: "get-latest-data"
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 4 * * 1"
  

jobs:
  get-latest-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requirements
      run: |
        pip install pandas pathlib
             
    - name: Get latest data
      run:  |
        cd ./code
        python ./get_latest_data.py
        
    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/KITmetricslab/RESPINOW-Data.git > /dev/null 2>&1
        git pull origin main
        git add --all
        git commit --allow-empty -m "Get latest data"
        
    - name: Push changes
      run: |
        git push --quiet --set-upstream origin HEAD:main
        echo "pushed to github"
