name: "get-RespVir-data"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"
  

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install requirements
      run: |
        pip3 install -r .github/workflows/requirements_respvir.txt
             
    - name: Get data
      env:
        RESPVIR: ${{ secrets.RESPVIR }}
      run:  |
        cd ./code
        python3 ./get_respvir.py
