name: "get-RespVir-data"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Install dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install requirements
      run: |
        pip3 install -r .github/workflows/requirements_respvir.txt
        
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
          r-version: 4.1.0
             
    - name: Get data
      env:
        RESPVIR: ${{ secrets.RESPVIR }}
      run:  |
        cd ./code
        python3 ./get_respvir.py
        cd ..
        Rscript code/process_respvir.R
