name: "reporting-triangle-NRZ"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"   
  

jobs:
  reporting-triangle-NRZ:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install requirements
      run: |
        pip3 install -r .github/workflows/requirements.txt
             
    - name: Create reporting triangle
      run:  |
        cd ./code
        python3 ./reporting_triangle.py
        
    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/KITmetricslab/RESPINOW-Data.git > /dev/null 2>&1
        git pull origin main
        git add --all
        git commit --allow-empty -m "Update reporting triangles"
        
    - name: Push changes
      run: |
        git push --quiet --set-upstream origin HEAD:main
        echo "pushed to github"
